project:
  type: website
  output-dir: blog

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hubersam/hubersam.github.io/
  sidebar:
    search: true
format:
  html:
    theme: cosmo
    css: styles.css